### ISSUE TITLE
@translate decorator fails when it is inherited?

### ISSUE THREAD

**Issue by timmartin19** [vertical-knowledge/ripozo#10]
File "/Users/martin/oss/ripozo/ripozo/viewsets/constructor.py", line 30, in __new__
        mcs._register_class(klass)
      File "/Users/martin/oss/ripozo/ripozo/viewsets/constructor.py", line 55, in _register_class
        method.cls = klass
    AttributeError: 'instancemethod' object has no attribute 'cls'

Came from a third level inherited class

    from ripozo.utilities import pick_processor
    from ripozo.viewsets.restmixins import RetrieveUpdate
    
    class UserResource(RetrieveUpdate):
        _pks = ['username']
        _preprocessors = [picky_processor(login_required, exclude=['login_user']),
                          picky_processor(admin_required, include=['update'])]
        _resource_name = 'user'
        _manager = UserManager
    
    class UserIdResource(UserResource):
        _pks = ['id']
        _resource_name = 'user_id'

**Comment by joshuag** [comment]
Make sure that you're using `wraps` from functools
