### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by cblegare** [vertical-knowledge/ripozo#71]
What's the recommended way for providing a swagger documentation of a ripozo-powered API?

**Comment by timmartin19** [comment]
So I'm not super familiar with the Swagger spec, but I think you would want to access the `ResourceMetaClass` singleton and grab the `registered_names_map`.  From there you should have access to all of the resources available and the information necessary to auto-generate the swagger documentation.  Let me know if you end up writing something as I would love to be involved.
